POST http://localhost:10001/directors/
Content-Type: application/json

{
  "name": "superka"
}

###

GET http://localhost:10001/directors/
Accept: application/json

###

GET http://localhost:10001/directors/5
Accept: application/json

###

PUT http://localhost:10001/directors/1
Accept: application/json
Content-Type: application/json

{
  "name": "kusturica"
}

###

DELETE http://localhost:10001/directors/21
Accept: application/json

###

PATCH http://localhost:10001/directors/1
Accept: application/json
Content-Type: application/json

{
  "name": "superka"
}

###